apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apiwiz-virtualservice
  namespace: dev
spec:
  gateways:
  - apiwiz-system/apiwiz-gateway
  hosts:
  - apiwiz.io
  - vinay-apibuilder.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: apibuilder-agent
        port:
          number: 9020
