apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apiwiz-virtualservice
  namespace: apiwiz-system
spec:
  gateways:
  - apiwiz-system/apiwiz-gateway
  hosts:
  - apiwiz.io
  - apibuilder.com
  http:
  - route:
    - destination:
        host: apibuilder-agent
        port:
          number: 8000
