apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: apiwiz-gateway
  namespace: apiwiz-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.apiwiz.io'
    port:
      name: https-apiwiz
      number: 443
      protocol: HTTPS
    tls:
      credentialName: apiwiz-credential-2024
      mode: SIMPLE
  - hosts:
    - mock.apiwiz.io
    port:
      name: https-mock-api
      number: 443
      protocol: HTTPS
    tls:
      credentialName: apiwiz-credential-2024
      mode: SIMPLE
  - hosts:
    - '*.apiwiz.io'
    port:
      name: http-apiwiz
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - varun-apibuilder.com
    port:
      name: https-acme-team-gcp-stage-1714732625092
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - varun-apibuilder.com
    port:
      name: https-acme-team-gcp-stage-1714732625092
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1714732625086
      mode: SIMPLE
  - hosts:
    - builder-test.ICIC.com
    port:
      name: https-acme-team-gcp-stage-1715227613569
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - builder-test.ICIC.com
    port:
      name: https-acme-team-gcp-stage-1715227613569
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1715227613561
      mode: SIMPLE
