apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: apiwiz-gateway
  namespace: apiwiz-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.apiwiz.io'
    port:
      name: https-apiwiz
      number: 443
      protocol: HTTPS
    tls:
      credentialName: apiwiz-credential-2024
      mode: SIMPLE
  - hosts:
    - mock.apiwiz.io
    port:
      name: https-mock-api
      number: 443
      protocol: HTTPS
    tls:
      credentialName: apiwiz-credential-2024
      mode: SIMPLE
  - hosts:
    - '*.apiwiz.io'
    port:
      name: http-apiwiz
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - varun-apibuilder.com
    port:
      name: https-acme-team-gcp-stage-1714732625092
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - varun-apibuilder.com
    port:
      name: https-acme-team-gcp-stage-1714732625092
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1714732625086
      mode: SIMPLE
  - hosts:
    - builder-test.ICIC.com
    port:
      name: https-acme-team-gcp-stage-1715240079278
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - builder-test.ICIC.com
    port:
      name: https-acme-team-gcp-stage-1715240079278
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1715240079271
      mode: SIMPLE
  - hosts:
    - testinng-builder.ICIC.com
    port:
      name: https-acme-team-gcp-stage-1715244675853
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - testinng-builder.ICIC.com
    port:
      name: https-acme-team-gcp-stage-1715244675853
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1715244675790
      mode: SIMPLE
  - hosts:
    - testing2-builder.ICIC.com
    port:
      name: https-acme-team-gcp-stage-1715244929317
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - testing2-builder.ICIC.com
    port:
      name: https-acme-team-gcp-stage-1715244929317
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1715244929175
      mode: SIMPLE
  - hosts:
    - acme.apibuilder-test.com
    port:
      name: https-acme-team-gcp-stage-1715252627990
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - acme.apibuilder-test.com
    port:
      name: https-acme-team-gcp-stage-1715252627990
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1715252627280
      mode: SIMPLE
  - hosts:
    - testing-builder.itorix.com
    port:
      name: https-acme-team-gcp-stage-1715335126533
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - testing-builder.itorix.com
    port:
      name: https-acme-team-gcp-stage-1715335126533
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1715335125735
      mode: SIMPLE
  - hosts:
    - icici.com
    port:
      name: https-acme-team-gcp-stage-1715426575537
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - icici.com
    port:
      name: https-acme-team-gcp-stage-1715426575537
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1715426575330
      mode: SIMPLE
  - hosts:
    - testing-builder.itorix.com
    port:
      name: https-acme-team-gcp-stage-1715521998875
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - testing-builder.itorix.com
    port:
      name: https-acme-team-gcp-stage-1715521998875
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1715521998694
      mode: SIMPLE
