apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: apiwiz-gateway
  namespace: dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.apiwiz.io'
    port:
      name: https-apiwiz
      number: 443
      protocol: HTTPS
    tls:
      credentialName: apiwiz-credential-2024
      mode: SIMPLE
  - hosts:
    - mock.apiwiz.io
    port:
      name: https-mock-api
      number: 443
      protocol: HTTPS
    tls:
      credentialName: apiwiz-credential-2024
      mode: SIMPLE
  - hosts:
    - '*.apiwiz.io'
    port:
      name: http-apiwiz
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - vinay-apibuilder.com
    port:
      name: https-acme-team-gcp-stage-1714731524581
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - vinay-apibuilder.com
    port:
      name: https-acme-team-gcp-stage-1714731524581
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1714731524567
      mode: SIMPLE
  - hosts:
    - shridhara-apibuilder.com
    port:
      name: https-acme-team-gcp-stage-1714732101195
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - shridhara-apibuilder.com
    port:
      name: https-acme-team-gcp-stage-1714732101195
      number: 443
      protocol: HTTPS
    tls:
      credentialName: acme-team-gcp-stage-1714732101178
      mode: SIMPLE
